// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: example.proto

package example

import (
	_ "github.com/lwc/protoc-gen-benum"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enum1 int32

const (
	Enum1_PROFILE Enum1 = 0
	Enum1_BILLING Enum1 = 1
	Enum1_LEGAL   Enum1 = 2
)

// Enum value maps for Enum1.
var (
	Enum1_name = map[int32]string{
		0: "PROFILE",
		1: "BILLING",
		2: "LEGAL",
	}
	Enum1_value = map[string]int32{
		"PROFILE": 0,
		"BILLING": 1,
		"LEGAL":   2,
	}
)

func (x Enum1) Enum() *Enum1 {
	p := new(Enum1)
	*p = x
	return p
}

func (x Enum1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Enum1) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[0].Descriptor()
}

func (Enum1) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[0]
}

func (x Enum1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Enum1.Descriptor instead.
func (Enum1) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

type EchoResponse_Enum2 int32

const (
	EchoResponse_PROFILE EchoResponse_Enum2 = 0
	EchoResponse_BILLING EchoResponse_Enum2 = 1
	EchoResponse_LEGAL   EchoResponse_Enum2 = 2
)

// Enum value maps for EchoResponse_Enum2.
var (
	EchoResponse_Enum2_name = map[int32]string{
		0: "PROFILE",
		1: "BILLING",
		2: "LEGAL",
	}
	EchoResponse_Enum2_value = map[string]int32{
		"PROFILE": 0,
		"BILLING": 1,
		"LEGAL":   2,
	}
)

func (x EchoResponse_Enum2) Enum() *EchoResponse_Enum2 {
	p := new(EchoResponse_Enum2)
	*p = x
	return p
}

func (x EchoResponse_Enum2) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EchoResponse_Enum2) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[1].Descriptor()
}

func (EchoResponse_Enum2) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[1]
}

func (x EchoResponse_Enum2) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EchoResponse_Enum2.Descriptor instead.
func (EchoResponse_Enum2) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1, 0}
}

type EchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Turkey  Enum1  `protobuf:"varint,2,opt,name=turkey,proto3,enum=ninety_nine.sdk.test.Enum1" json:"turkey,omitempty"`
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoRequest) GetTurkey() Enum1 {
	if x != nil {
		return x.Turkey
	}
	return Enum1_PROFILE
}

type EchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string             `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Snakes  EchoResponse_Enum2 `protobuf:"varint,2,opt,name=snakes,proto3,enum=ninety_nine.sdk.test.EchoResponse_Enum2" json:"snakes,omitempty"`
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoResponse) GetSnakes() EchoResponse_Enum2 {
	if x != nil {
		return x.Snakes
	}
	return EchoResponse_PROFILE
}

var File_example_proto protoreflect.FileDescriptor

var file_example_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x14, 0x6e, 0x69, 0x6e, 0x65, 0x74, 0x79, 0x5f, 0x6e, 0x69, 0x6e, 0x65, 0x2e, 0x73, 0x64, 0x6b,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x62, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x0b, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x74,
	0x75, 0x72, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6e, 0x69,
	0x6e, 0x65, 0x74, 0x79, 0x5f, 0x6e, 0x69, 0x6e, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x31, 0x52, 0x06, 0x74, 0x75, 0x72, 0x6b, 0x65, 0x79,
	0x22, 0xa5, 0x01, 0x0a, 0x0c, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x73,
	0x6e, 0x61, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x6e, 0x69,
	0x6e, 0x65, 0x74, 0x79, 0x5f, 0x6e, 0x69, 0x6e, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x45, 0x6e, 0x75, 0x6d, 0x32, 0x52, 0x06, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x73, 0x22, 0x39, 0x0a,
	0x05, 0x45, 0x6e, 0x75, 0x6d, 0x32, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c,
	0x45, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x49, 0x4c, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x1a, 0x0b, 0x9a, 0xb5, 0x18, 0x07, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x09, 0x0a,
	0x05, 0x4c, 0x45, 0x47, 0x41, 0x4c, 0x10, 0x02, 0x2a, 0x4c, 0x0a, 0x05, 0x45, 0x6e, 0x75, 0x6d,
	0x31, 0x12, 0x20, 0x0a, 0x07, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x1a, 0x13,
	0x9a, 0xb5, 0x18, 0x05, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0xa2, 0xb5, 0x18, 0x06, 0x74, 0x75, 0x72,
	0x6b, 0x65, 0x79, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x49, 0x4c, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x14, 0x0a, 0x05, 0x4c, 0x45, 0x47, 0x41, 0x4c, 0x10, 0x02, 0x1a, 0x09, 0xa2, 0xb5, 0x18,
	0x05, 0x62, 0x6c, 0x61, 0x72, 0x67, 0x32, 0x58, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4d, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x21, 0x2e, 0x6e, 0x69, 0x6e, 0x65,
	0x74, 0x79, 0x5f, 0x6e, 0x69, 0x6e, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6e,
	0x69, 0x6e, 0x65, 0x74, 0x79, 0x5f, 0x6e, 0x69, 0x6e, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x77, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x62, 0x65,
	0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData = file_example_proto_rawDesc
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_proto_rawDescData)
	})
	return file_example_proto_rawDescData
}

var file_example_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_example_proto_goTypes = []interface{}{
	(Enum1)(0),              // 0: ninety_nine.sdk.test.Enum1
	(EchoResponse_Enum2)(0), // 1: ninety_nine.sdk.test.EchoResponse.Enum2
	(*EchoRequest)(nil),     // 2: ninety_nine.sdk.test.EchoRequest
	(*EchoResponse)(nil),    // 3: ninety_nine.sdk.test.EchoResponse
}
var file_example_proto_depIdxs = []int32{
	0, // 0: ninety_nine.sdk.test.EchoRequest.turkey:type_name -> ninety_nine.sdk.test.Enum1
	1, // 1: ninety_nine.sdk.test.EchoResponse.snakes:type_name -> ninety_nine.sdk.test.EchoResponse.Enum2
	2, // 2: ninety_nine.sdk.test.Service.Echo:input_type -> ninety_nine.sdk.test.EchoRequest
	3, // 3: ninety_nine.sdk.test.Service.Echo:output_type -> ninety_nine.sdk.test.EchoResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		EnumInfos:         file_example_proto_enumTypes,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_rawDesc = nil
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
