// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Enum1 int32

const (
	Enum1_PROFILE Enum1 = 0
	Enum1_BILLING Enum1 = 1
	Enum1_LEGAL   Enum1 = 2
)

var Enum1_name = map[int32]string{
	0: "PROFILE",
	1: "BILLING",
	2: "LEGAL",
}

var Enum1_value = map[string]int32{
	"PROFILE": 0,
	"BILLING": 1,
	"LEGAL":   2,
}

func (x Enum1) String() string {
	return proto.EnumName(Enum1_name, int32(x))
}

func (Enum1) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

type EchoResponse_Enum2 int32

const (
	EchoResponse_PROFILE EchoResponse_Enum2 = 0
	EchoResponse_BILLING EchoResponse_Enum2 = 1
	EchoResponse_LEGAL   EchoResponse_Enum2 = 2
)

var EchoResponse_Enum2_name = map[int32]string{
	0: "PROFILE",
	1: "BILLING",
	2: "LEGAL",
}

var EchoResponse_Enum2_value = map[string]int32{
	"PROFILE": 0,
	"BILLING": 1,
	"LEGAL":   2,
}

func (x EchoResponse_Enum2) String() string {
	return proto.EnumName(EchoResponse_Enum2_name, int32(x))
}

func (EchoResponse_Enum2) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1, 0}
}

type EchoRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Turkey               Enum1    `protobuf:"varint,2,opt,name=turkey,proto3,enum=ninety_nine.sdk.test.Enum1" json:"turkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EchoRequest) GetTurkey() Enum1 {
	if m != nil {
		return m.Turkey
	}
	return Enum1_PROFILE
}

type EchoResponse struct {
	Message              string             `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Snakes               EchoResponse_Enum2 `protobuf:"varint,2,opt,name=snakes,proto3,enum=ninety_nine.sdk.test.EchoResponse_Enum2" json:"snakes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EchoResponse) GetSnakes() EchoResponse_Enum2 {
	if m != nil {
		return m.Snakes
	}
	return EchoResponse_PROFILE
}

func init() {
	proto.RegisterEnum("ninety_nine.sdk.test.Enum1", Enum1_name, Enum1_value)
	proto.RegisterEnum("ninety_nine.sdk.test.EchoResponse_Enum2", EchoResponse_Enum2_name, EchoResponse_Enum2_value)
	proto.RegisterType((*EchoRequest)(nil), "ninety_nine.sdk.test.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "ninety_nine.sdk.test.EchoResponse")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd1, 0x4f, 0x4b, 0xbc, 0x40,
	0x18, 0x07, 0xf0, 0x9f, 0xcb, 0xcf, 0x15, 0xc7, 0x0a, 0x99, 0xf6, 0x30, 0xd8, 0xc5, 0x3c, 0x49,
	0x07, 0x61, 0xdd, 0x53, 0xb7, 0x5a, 0xb0, 0x45, 0x98, 0xfe, 0x60, 0x97, 0x88, 0x20, 0x74, 0x7b,
	0x30, 0x51, 0x47, 0x73, 0xc6, 0x68, 0xdf, 0xca, 0x1e, 0x17, 0x7a, 0x09, 0xbe, 0xbf, 0xf0, 0x4f,
	0xcb, 0x1e, 0x6a, 0x3b, 0x89, 0xc3, 0xf3, 0x7c, 0x9e, 0xf9, 0xce, 0x83, 0x0e, 0xe1, 0x23, 0xcc,
	0xcb, 0x0c, 0x9c, 0xb2, 0x2a, 0x44, 0x81, 0x27, 0x2c, 0x61, 0x20, 0x56, 0xcf, 0xed, 0xc7, 0xe1,
	0x2f, 0xa9, 0x23, 0x80, 0x0b, 0x43, 0x8b, 0x80, 0xd5, 0x79, 0x5f, 0x62, 0x3d, 0x21, 0xcd, 0x5b,
	0xbe, 0x16, 0x01, 0xbc, 0xd5, 0xc0, 0x05, 0x26, 0x48, 0xc9, 0x81, 0xf3, 0x30, 0x06, 0x22, 0x99,
	0x92, 0xad, 0x06, 0xdf, 0xbf, 0x78, 0x86, 0xc6, 0xa2, 0xae, 0x52, 0x58, 0x91, 0x91, 0x29, 0xd9,
	0x47, 0xee, 0x89, 0xf3, 0x13, 0xee, 0x78, 0xac, 0xce, 0xa7, 0xc1, 0x50, 0x6a, 0x7d, 0x4a, 0xe8,
	0xa0, 0xe7, 0x79, 0x59, 0x30, 0x0e, 0x7b, 0xfc, 0x0b, 0x34, 0xe6, 0x2c, 0x4c, 0x81, 0x0f, 0xbe,
	0xfd, 0x8b, 0xbf, 0xa3, 0x75, 0xc3, 0xdc, 0x60, 0xe8, 0xb3, 0xce, 0x91, 0xdc, 0x1d, 0x60, 0x0d,
	0x29, 0x77, 0xc1, 0xed, 0x95, 0x4f, 0x3d, 0xfd, 0x5f, 0x3b, 0x71, 0xee, 0x53, 0xea, 0xdf, 0x2c,
	0x74, 0xc9, 0xd0, 0xd6, 0x0d, 0x51, 0xa2, 0x24, 0xcb, 0x12, 0x16, 0x63, 0x15, 0xc9, 0xd4, 0x5b,
	0x5c, 0x52, 0x7d, 0x74, 0x46, 0xfb, 0xd6, 0x29, 0x36, 0x77, 0x5a, 0x8d, 0xe3, 0x75, 0x43, 0xe4,
	0x0e, 0xdf, 0x34, 0x64, 0x88, 0xd4, 0xe2, 0x5b, 0x0f, 0x4f, 0xb6, 0x84, 0xa1, 0x6e, 0x1a, 0x22,
	0x47, 0x59, 0x58, 0xc5, 0xee, 0x03, 0x52, 0xee, 0xa1, 0x7a, 0x4f, 0x96, 0x80, 0xaf, 0xd1, 0xff,
	0xf6, 0xc6, 0xf8, 0x74, 0x5f, 0x9a, 0xee, 0xe9, 0x0d, 0xeb, 0xef, 0xc0, 0x73, 0xf5, 0x51, 0x19,
	0x36, 0x1c, 0x8d, 0xbb, 0xfd, 0xcd, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xc4, 0x51, 0x39,
	0xf3, 0x01, 0x00, 0x00,
}
