// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nestedonly.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OutResponse_Enum2 int32

const (
	OutResponse_PROFILE OutResponse_Enum2 = 0
	OutResponse_BILLING OutResponse_Enum2 = 1
	OutResponse_LEGAL   OutResponse_Enum2 = 2
)

var OutResponse_Enum2_name = map[int32]string{
	0: "PROFILE",
	1: "BILLING",
	2: "LEGAL",
}

var OutResponse_Enum2_value = map[string]int32{
	"PROFILE": 0,
	"BILLING": 1,
	"LEGAL":   2,
}

func (x OutResponse_Enum2) String() string {
	return proto.EnumName(OutResponse_Enum2_name, int32(x))
}

func (OutResponse_Enum2) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6f5b5c0caaa4bdb4, []int{1, 0}
}

type InRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InRequest) Reset()         { *m = InRequest{} }
func (m *InRequest) String() string { return proto.CompactTextString(m) }
func (*InRequest) ProtoMessage()    {}
func (*InRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5b5c0caaa4bdb4, []int{0}
}

func (m *InRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InRequest.Unmarshal(m, b)
}
func (m *InRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InRequest.Marshal(b, m, deterministic)
}
func (m *InRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InRequest.Merge(m, src)
}
func (m *InRequest) XXX_Size() int {
	return xxx_messageInfo_InRequest.Size(m)
}
func (m *InRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InRequest proto.InternalMessageInfo

func (m *InRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type OutResponse struct {
	Message              string            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Snakes               OutResponse_Enum2 `protobuf:"varint,2,opt,name=snakes,proto3,enum=ninety_nine.sdk.test.OutResponse_Enum2" json:"snakes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OutResponse) Reset()         { *m = OutResponse{} }
func (m *OutResponse) String() string { return proto.CompactTextString(m) }
func (*OutResponse) ProtoMessage()    {}
func (*OutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5b5c0caaa4bdb4, []int{1}
}

func (m *OutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutResponse.Unmarshal(m, b)
}
func (m *OutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutResponse.Marshal(b, m, deterministic)
}
func (m *OutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutResponse.Merge(m, src)
}
func (m *OutResponse) XXX_Size() int {
	return xxx_messageInfo_OutResponse.Size(m)
}
func (m *OutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OutResponse proto.InternalMessageInfo

func (m *OutResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OutResponse) GetSnakes() OutResponse_Enum2 {
	if m != nil {
		return m.Snakes
	}
	return OutResponse_PROFILE
}

func init() {
	proto.RegisterEnum("ninety_nine.sdk.test.OutResponse_Enum2", OutResponse_Enum2_name, OutResponse_Enum2_value)
	proto.RegisterType((*InRequest)(nil), "ninety_nine.sdk.test.InRequest")
	proto.RegisterType((*OutResponse)(nil), "ninety_nine.sdk.test.OutResponse")
}

func init() { proto.RegisterFile("nestedonly.proto", fileDescriptor_6f5b5c0caaa4bdb4) }

var fileDescriptor_6f5b5c0caaa4bdb4 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x4b, 0x2d, 0x2e,
	0x49, 0x4d, 0xc9, 0xcf, 0xcb, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc9, 0xcb,
	0xcc, 0x4b, 0x2d, 0xa9, 0x8c, 0x07, 0x51, 0x7a, 0xc5, 0x29, 0xd9, 0x7a, 0x25, 0xa9, 0xc5, 0x25,
	0x52, 0xdc, 0x49, 0xa9, 0x79, 0xa5, 0xb9, 0x10, 0x25, 0x4a, 0xaa, 0x5c, 0x9c, 0x9e, 0x79, 0x41,
	0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0xd2, 0x62, 0x46, 0x2e, 0x6e, 0xff,
	0xd2, 0x92, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xdc, 0x2a, 0x85, 0xec, 0xb9, 0xd8,
	0x8a, 0xf3, 0x12, 0xb3, 0x53, 0x8b, 0x25, 0x98, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0xd4, 0xf5, 0xb0,
	0x39, 0x42, 0x0f, 0xc9, 0x30, 0x3d, 0xd7, 0xbc, 0xd2, 0x5c, 0xa3, 0x20, 0xa8, 0x36, 0x25, 0x4b,
	0x2e, 0x56, 0xb0, 0x80, 0x10, 0x37, 0x17, 0x7b, 0x40, 0x90, 0xbf, 0x9b, 0xa7, 0x8f, 0xab, 0x00,
	0x03, 0xc8, 0x42, 0x27, 0x4f, 0x1f, 0x1f, 0x4f, 0x3f, 0x77, 0x01, 0x46, 0x29, 0xee, 0x59, 0x5b,
	0x25, 0xd8, 0x93, 0x32, 0x73, 0x72, 0x32, 0xf3, 0xd2, 0x85, 0x38, 0xb9, 0x58, 0x7d, 0x5c, 0xdd,
	0x1d, 0x7d, 0x04, 0x98, 0x8c, 0xa2, 0xb9, 0x78, 0x83, 0x53, 0x93, 0xf3, 0xf3, 0x52, 0x82, 0x53,
	0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0xbc, 0xb8, 0x58, 0x5c, 0x93, 0x33, 0xf2, 0x85, 0xe4, 0xb1,
	0x3b, 0x02, 0xee, 0x73, 0x29, 0x45, 0x82, 0xae, 0x74, 0xe2, 0x8c, 0x62, 0x4f, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0x4d, 0x62, 0x03, 0x87, 0x9d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x93,
	0x99, 0x7a, 0x72, 0x01, 0x00, 0x00,
}
