// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: nestedonly.proto

package example

import (
	_ "github.com/lwc/protoc-gen-benum"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutResponse_Enum2 int32

const (
	OutResponse_PROFILE OutResponse_Enum2 = 0
	OutResponse_BILLING OutResponse_Enum2 = 1
	OutResponse_LEGAL   OutResponse_Enum2 = 2
)

// Enum value maps for OutResponse_Enum2.
var (
	OutResponse_Enum2_name = map[int32]string{
		0: "PROFILE",
		1: "BILLING",
		2: "LEGAL",
	}
	OutResponse_Enum2_value = map[string]int32{
		"PROFILE": 0,
		"BILLING": 1,
		"LEGAL":   2,
	}
)

func (x OutResponse_Enum2) Enum() *OutResponse_Enum2 {
	p := new(OutResponse_Enum2)
	*p = x
	return p
}

func (x OutResponse_Enum2) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutResponse_Enum2) Descriptor() protoreflect.EnumDescriptor {
	return file_nestedonly_proto_enumTypes[0].Descriptor()
}

func (OutResponse_Enum2) Type() protoreflect.EnumType {
	return &file_nestedonly_proto_enumTypes[0]
}

func (x OutResponse_Enum2) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutResponse_Enum2.Descriptor instead.
func (OutResponse_Enum2) EnumDescriptor() ([]byte, []int) {
	return file_nestedonly_proto_rawDescGZIP(), []int{1, 0}
}

type InRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *InRequest) Reset() {
	*x = InRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nestedonly_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InRequest) ProtoMessage() {}

func (x *InRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nestedonly_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InRequest.ProtoReflect.Descriptor instead.
func (*InRequest) Descriptor() ([]byte, []int) {
	return file_nestedonly_proto_rawDescGZIP(), []int{0}
}

func (x *InRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Snakes  OutResponse_Enum2 `protobuf:"varint,2,opt,name=snakes,proto3,enum=ninety_nine.sdk.test.OutResponse_Enum2" json:"snakes,omitempty"`
}

func (x *OutResponse) Reset() {
	*x = OutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nestedonly_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutResponse) ProtoMessage() {}

func (x *OutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nestedonly_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutResponse.ProtoReflect.Descriptor instead.
func (*OutResponse) Descriptor() ([]byte, []int) {
	return file_nestedonly_proto_rawDescGZIP(), []int{1}
}

func (x *OutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OutResponse) GetSnakes() OutResponse_Enum2 {
	if x != nil {
		return x.Snakes
	}
	return OutResponse_PROFILE
}

var File_nestedonly_proto protoreflect.FileDescriptor

var file_nestedonly_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x6f, 0x6e, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x6e, 0x69, 0x6e, 0x65, 0x74, 0x79, 0x5f, 0x6e, 0x69, 0x6e, 0x65, 0x2e,
	0x73, 0x64, 0x6b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x62, 0x65, 0x6e, 0x75, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x09, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa3, 0x01, 0x0a,
	0x0b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x6e, 0x69, 0x6e, 0x65, 0x74, 0x79, 0x5f,
	0x6e, 0x69, 0x6e, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x75,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x32, 0x52,
	0x06, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x05, 0x45, 0x6e, 0x75, 0x6d, 0x32,
	0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x18, 0x0a,
	0x07, 0x42, 0x49, 0x4c, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x1a, 0x0b, 0x9a, 0xb5, 0x18, 0x07,
	0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x45, 0x47, 0x41, 0x4c,
	0x10, 0x02, 0x32, 0x5b, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x1f, 0x2e, 0x6e, 0x69,
	0x6e, 0x65, 0x74, 0x79, 0x5f, 0x6e, 0x69, 0x6e, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6e,
	0x69, 0x6e, 0x65, 0x74, 0x79, 0x5f, 0x6e, 0x69, 0x6e, 0x65, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x77,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x62, 0x65, 0x6e,
	0x75, 0x6d, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_nestedonly_proto_rawDescOnce sync.Once
	file_nestedonly_proto_rawDescData = file_nestedonly_proto_rawDesc
)

func file_nestedonly_proto_rawDescGZIP() []byte {
	file_nestedonly_proto_rawDescOnce.Do(func() {
		file_nestedonly_proto_rawDescData = protoimpl.X.CompressGZIP(file_nestedonly_proto_rawDescData)
	})
	return file_nestedonly_proto_rawDescData
}

var file_nestedonly_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nestedonly_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nestedonly_proto_goTypes = []interface{}{
	(OutResponse_Enum2)(0), // 0: ninety_nine.sdk.test.OutResponse.Enum2
	(*InRequest)(nil),      // 1: ninety_nine.sdk.test.InRequest
	(*OutResponse)(nil),    // 2: ninety_nine.sdk.test.OutResponse
}
var file_nestedonly_proto_depIdxs = []int32{
	0, // 0: ninety_nine.sdk.test.OutResponse.snakes:type_name -> ninety_nine.sdk.test.OutResponse.Enum2
	1, // 1: ninety_nine.sdk.test.SecondService.Echo:input_type -> ninety_nine.sdk.test.InRequest
	2, // 2: ninety_nine.sdk.test.SecondService.Echo:output_type -> ninety_nine.sdk.test.OutResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nestedonly_proto_init() }
func file_nestedonly_proto_init() {
	if File_nestedonly_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nestedonly_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nestedonly_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nestedonly_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nestedonly_proto_goTypes,
		DependencyIndexes: file_nestedonly_proto_depIdxs,
		EnumInfos:         file_nestedonly_proto_enumTypes,
		MessageInfos:      file_nestedonly_proto_msgTypes,
	}.Build()
	File_nestedonly_proto = out.File
	file_nestedonly_proto_rawDesc = nil
	file_nestedonly_proto_goTypes = nil
	file_nestedonly_proto_depIdxs = nil
}
